# Generated by Django 2.2.8 on 2020-01-06 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_tabuladump'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TabulaDump',
        ),
    ]
