# Generated by Django 2.2 on 2019-11-08 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_name', models.CharField(max_length=50)),
                ('percentage', models.DecimalField(decimal_places=1, max_digits=4)),
                ('uses_worst_result', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=15)),
                ('academic_year', models.CharField(choices=[('19/20', '19/20'), ('18/19', '18/19'), ('17/18', '17/18'), ('16/17', '16/17'), ('15/16', '15/16'), ('14/15', '14/15')], default='19/20', max_length=5)),
                ('faculty', models.CharField(max_length=50)),
                ('module_code', models.CharField(max_length=10)),
                ('module_name', models.CharField(max_length=100)),
                ('cats', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Assessment_group_name', models.CharField(max_length=50)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.Module')),
            ],
        ),
    ]
