# Generated by Django 2.2 on 2019-11-08 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0002_auto_20191108_1512'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='cats',
            new_name='module_cats',
        ),
    ]
