# Generated by Django 2.2 on 2019-12-06 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0002_auto_20191205_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='level',
        ),
    ]
