# Generated by Django 2.2 on 2019-11-08 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0004_auto_20191108_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='assessment_name',
            field=models.CharField(max_length=100),
        ),
    ]
