# Generated by Django 2.2 on 2019-11-08 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0005_auto_20191108_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='module_cats',
        ),
        migrations.AddField(
            model_name='assessmentgroup',
            name='module_cats',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
