# Generated by Django 2.2 on 2019-12-28 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0006_auto_20191211_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='academic_year',
            field=models.CharField(choices=[('19/20', '19/20'), ('18/19', '18/19'), ('17/18', '17/18')], default='19/20', max_length=5),
        ),
        migrations.AlterField(
            model_name='undefinedmodule',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unknown_modules', to=settings.AUTH_USER_MODEL),
        ),
    ]
