# Generated by Django 2.2 on 2019-12-28 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0007_auto_20191228_1900'),
        ('modules', '0007_auto_20191212_0013'),
    ]

    operations = [
    ]
