# Generated by Django 2.2 on 2019-11-08 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0008_auto_20191108_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentgroup',
            name='module_cats',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
    ]
