# Generated by Django 2.2 on 2019-12-28 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0008_auto_20191228_2032'),
        ('modules', '0008_merge_20191228_1901'),
    ]

    operations = [
    ]
