# Generated by Django 2.2.8 on 2020-01-06 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0009_merge_20191228_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='academic_year',
            field=models.CharField(choices=[('19/20', '19/20'), ('18/19', '18/19'), ('17/18', '17/18'), ('16/17', '16/17')], default='19/20', max_length=5),
        ),
    ]
