# Generated by Django 2.2 on 2019-11-14 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0009_auto_20191108_1815'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessmentgroup',
            options={'ordering': ['assessment_group_name']},
        ),
    ]
