# Generated by Django 2.2 on 2019-11-28 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0010_auto_20191114_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentgroup',
            name='assessment_group_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='module',
            name='module_name',
            field=models.CharField(max_length=200),
        ),
    ]
