# Generated by Django 2.2 on 2019-11-28 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0011_auto_20191128_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='faculty',
            field=models.CharField(max_length=100),
        ),
    ]
